// Generated by gencpp from file Total_msgs/Control.msg
// DO NOT EDIT!


#ifndef TOTAL_MSGS_MESSAGE_CONTROL_H
#define TOTAL_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Total_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : s16_throttle(0)
    , s16_steering(0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : s16_throttle(0)
    , s16_steering(0)  {
  (void)_alloc;
    }



   typedef int16_t _s16_throttle_type;
  _s16_throttle_type s16_throttle;

   typedef int16_t _s16_steering_type;
  _s16_steering_type s16_steering;





  typedef boost::shared_ptr< ::Total_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Total_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::Total_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::Total_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::Total_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Total_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Total_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Total_msgs::Control_<ContainerAllocator1> & lhs, const ::Total_msgs::Control_<ContainerAllocator2> & rhs)
{
  return lhs.s16_throttle == rhs.s16_throttle &&
    lhs.s16_steering == rhs.s16_steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Total_msgs::Control_<ContainerAllocator1> & lhs, const ::Total_msgs::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Total_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Total_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Total_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Total_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Total_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Total_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Total_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Total_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8b835278dfb2031fe8ad479c5a2c137";
  }

  static const char* value(const ::Total_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8b835278dfb2031ULL;
  static const uint64_t static_value2 = 0xfe8ad479c5a2c137ULL;
};

template<class ContainerAllocator>
struct DataType< ::Total_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Total_msgs/Control";
  }

  static const char* value(const ::Total_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Total_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 s16_throttle\n"
"int16 s16_steering\n"
;
  }

  static const char* value(const ::Total_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Total_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s16_throttle);
      stream.next(m.s16_steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Total_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Total_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "s16_throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16_throttle);
    s << indent << "s16_steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16_steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOTAL_MSGS_MESSAGE_CONTROL_H
