// Generated by gencpp from file Jongseol/init.msg
// DO NOT EDIT!


#ifndef JONGSEOL_MESSAGE_INIT_H
#define JONGSEOL_MESSAGE_INIT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Jongseol
{
template <class ContainerAllocator>
struct init_
{
  typedef init_<ContainerAllocator> Type;

  init_()
    : init(0)  {
    }
  init_(const ContainerAllocator& _alloc)
    : init(0)  {
  (void)_alloc;
    }



   typedef int32_t _init_type;
  _init_type init;





  typedef boost::shared_ptr< ::Jongseol::init_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Jongseol::init_<ContainerAllocator> const> ConstPtr;

}; // struct init_

typedef ::Jongseol::init_<std::allocator<void> > init;

typedef boost::shared_ptr< ::Jongseol::init > initPtr;
typedef boost::shared_ptr< ::Jongseol::init const> initConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Jongseol::init_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Jongseol::init_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Jongseol::init_<ContainerAllocator1> & lhs, const ::Jongseol::init_<ContainerAllocator2> & rhs)
{
  return lhs.init == rhs.init;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Jongseol::init_<ContainerAllocator1> & lhs, const ::Jongseol::init_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Jongseol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Jongseol::init_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Jongseol::init_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jongseol::init_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jongseol::init_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jongseol::init_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jongseol::init_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Jongseol::init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f6ced171af8c7d52168d92bd6d3936e";
  }

  static const char* value(const ::Jongseol::init_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f6ced171af8c7d5ULL;
  static const uint64_t static_value2 = 0x2168d92bd6d3936eULL;
};

template<class ContainerAllocator>
struct DataType< ::Jongseol::init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Jongseol/init";
  }

  static const char* value(const ::Jongseol::init_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Jongseol::init_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 init\n"
;
  }

  static const char* value(const ::Jongseol::init_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Jongseol::init_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.init);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct init_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Jongseol::init_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Jongseol::init_<ContainerAllocator>& v)
  {
    s << indent << "init: ";
    Printer<int32_t>::stream(s, indent + "  ", v.init);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JONGSEOL_MESSAGE_INIT_H
