// Generated by gencpp from file Jongseol/obj.msg
// DO NOT EDIT!


#ifndef JONGSEOL_MESSAGE_OBJ_H
#define JONGSEOL_MESSAGE_OBJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Jongseol
{
template <class ContainerAllocator>
struct obj_
{
  typedef obj_<ContainerAllocator> Type;

  obj_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  obj_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _dx_type;
  _dx_type dx;

   typedef float _dy_type;
  _dy_type dy;

   typedef float _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::Jongseol::obj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Jongseol::obj_<ContainerAllocator> const> ConstPtr;

}; // struct obj_

typedef ::Jongseol::obj_<std::allocator<void> > obj;

typedef boost::shared_ptr< ::Jongseol::obj > objPtr;
typedef boost::shared_ptr< ::Jongseol::obj const> objConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Jongseol::obj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Jongseol::obj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Jongseol::obj_<ContainerAllocator1> & lhs, const ::Jongseol::obj_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Jongseol::obj_<ContainerAllocator1> & lhs, const ::Jongseol::obj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Jongseol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Jongseol::obj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Jongseol::obj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jongseol::obj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jongseol::obj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jongseol::obj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jongseol::obj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Jongseol::obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ebdf4fc16c563585927be0d949cdc5a";
  }

  static const char* value(const ::Jongseol::obj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ebdf4fc16c56358ULL;
  static const uint64_t static_value2 = 0x5927be0d949cdc5aULL;
};

template<class ContainerAllocator>
struct DataType< ::Jongseol::obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Jongseol/obj";
  }

  static const char* value(const ::Jongseol::obj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Jongseol::obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"float32 dx\n"
"float32 dy\n"
"float32 dz\n"
;
  }

  static const char* value(const ::Jongseol::obj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Jongseol::obj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Jongseol::obj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Jongseol::obj_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "dx: ";
    Printer<float>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<float>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<float>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JONGSEOL_MESSAGE_OBJ_H
