# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Jongseol/objs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import Jongseol.msg

class objs(genpy.Message):
  _md5sum = "789bc1e6255eb45d2bff2d818b83b6cb"
  _type = "Jongseol/objs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 num

obj[] obj
================================================================================
MSG: Jongseol/obj
float32 x
float32 y
float32 z

float32 dx
float32 dy
float32 dz"""
  __slots__ = ['num','obj']
  _slot_types = ['int32','Jongseol/obj[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       num,obj

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(objs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.num is None:
        self.num = 0
      if self.obj is None:
        self.obj = []
    else:
      self.num = 0
      self.obj = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.obj)
      buff.write(_struct_I.pack(length))
      for val1 in self.obj:
        _x = val1
        buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obj is None:
        self.obj = None
      end = 0
      start = end
      end += 4
      (self.num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obj = []
      for i in range(0, length):
        val1 = Jongseol.msg.obj()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz,) = _get_struct_6f().unpack(str[start:end])
        self.obj.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.obj)
      buff.write(_struct_I.pack(length))
      for val1 in self.obj:
        _x = val1
        buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obj is None:
        self.obj = None
      end = 0
      start = end
      end += 4
      (self.num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obj = []
      for i in range(0, length):
        val1 = Jongseol.msg.obj()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz,) = _get_struct_6f().unpack(str[start:end])
        self.obj.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
